spring:
  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:postgresql://localhost:5432/nomis_sync?sslmode=prefer'
    username: postgres
    password: postgres

hmpps-auth:
  url: "http://localhost:8090/auth"

hmpps.sqs:
  provider: localstack
  queues:
    domainevents:
      queueName: local_queue
      dlqName: local_dlq
      subscribeTopicId: domaineventsqueue
  topics:
    domaineventsqueue:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events_queue

feature:
  general-ledger-api:
    enabled: true
    test-prisoner-ids: A0251AB

general-ledger-api:
  url: http://localhost:8084
  client:
    id: hmpps-prisoner-finance-general-ledger-api
    secret: clientsecret