generic-service:
  nameOverride: hmpps-prisoner-finance-sync-api
  productId: "DPS099" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  serviceAccountName: hmpps-prisoner-finance-sync-api

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-prisoner-finance-sync-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-prisoner-finance-sync-api-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    # JAVA_TOOL_OPTIONS is set in the base image (hmpps-eclipse-temurin) with:
    #   -XX:MaxRAMPercentage=50.0
    # Uncomment below to override memory settings if needed.
    # Check resources.limits.memory is set appropriately.
    #
    # Percentage-based example:
    #   JAVA_TOOL_OPTIONS: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"
    #
    # Fixed memory example:
    #   JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-prisoner-finance-sync-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

    hmpps-prisoner-finance-general-ledger-api-client-creds:
      GENERAL_LEDGER_API_CLIENT_ID: 'API_CLIENT_ID'
      GENERAL_LEDGER_API_CLIENT_SECRET: 'API_CLIENT_SECRET'

    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_endpoint"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

    domain-events-prisoner-finance-sync-queue:
      HMPPS_SQS_QUEUES_DOMAINEVENTS_QUEUE_NAME: "sqs_queue_name"

    domain-events-prisoner-finance-sync-dlq:
      HMPPS_SQS_QUEUES_DOMAINEVENTS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-finance-sync-api
