---
# Per environment values which override defaults in hmpps-prisoner-finance-sync-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-finance-sync-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    GENERAL_LEDGER_API_URL: "https://prisoner-finance-general-ledger-api-dev.hmpps.service.justice.gov.uk"
    FEATURE_GENERAL_LEDGER_API_ENABLED: "true"
    FEATURE_GENERAL_LEDGER_API_TEST_PRISONER_IDS: A9971EC

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "hmpps-prisoner-finance-dev-prisoner_finance_sync_queue_for_domain_events"
    - "hmpps-prisoner-finance-dev-prisoner_finance_sync_queue_for_domain_events_dl"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: info-hmpps-prisoner-finance-sync-dev
