---
# Per environment values which override defaults in hmpps-prisoner-finance-sync-api/values.yaml

generic-service:
  ingress:
    host: prisoner-finance-sync-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    GENERAL_LEDGER_API_URL: "https://prisoner-finance-general-ledger-api.hmpps.service.justice.gov.uk"

  postgresDatabaseRestore:
    enabled: true
    timeout: 3590
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "hmpps-prisoner-finance-prod-prisoner_finance_sync_queue_for_domain_events"
    - "hmpps-prisoner-finance-prod-prisoner_finance_sync_queue_for_domain_events_dl"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: hmpps-prisoner-finance-sync-api

