---
# Per environment values which override defaults in hmpps-prisoner-finance-sync-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    enabled: true
    host: prisoner-finance-sync-api-dev.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        more_set_headers "Strict-Transport-Security: \"max-age=63072000; includeSubdomains; preload\"";
        if ($server_protocol !~ "^HTTP/2") {
          return 426;
        }

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "hmpps-prisoner-finance-dev-prisoner_finance_sync_queue_for_domain_events"
    - "hmpps-prisoner-finance-dev-prisoner_finance_sync_queue_for_domain_events_dl"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: info-hmpps-prisoner-finance-sync-dev
